affinity:
  podAntiAffinity: 
    preferredDuringSchedulingIgnoredDuringExecution: 
    - weight: 100  
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In 
            values:
            - odis-signer
        topologyKey: kubernetes.io/hostname
autoscaling:
  enabled: false
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
env:
  api:
    domainsAPIEnabled: true
    pnpAPIEnabled: true
  blockchain:
    blockchainApiKeyExistingSecret: odis-signer1-forno-key
    blockchainProvider: https://forno.celo.org
  db:
    cloudSqlProxy: false
    database: phoneNumberPrivacy
    host: odis-signer1-mainnet-db-postgresql-hl
    passwordExistingSecret: odis-signer1-db-password
    port: 5432
    type: postgres
    useSsl: false
    username: clabs
    poolMaxSize: 100
    timeout: 10000
  keystore:
    domainsKeyLatestVersion: null
    domainsKeyNameBase: odis-signer1-mainnet-domains
    gcp:
      projectID: celo-testnet-production
    pnpKeyLatestVersion: null
    pnpKeyNameBase: odis-signer1-mainnet-phoneNumberPrivacy
    type: GoogleSecretManager
  log:
    format: stackdriver
    level: trace
  odis:
    odisSignerTimeout: "10000"
    shouldMockAccountService: "false"
    shouldMockRequestService: "false"
    fullNodeTimeoutMs: 10000
  tracing:
    enabled: true
    endpoint: "http://grafana-agent.monitoring:14268/api/traces"
    serviceName: "odis-signer1-mainnet-k8s"
fullnameOverride: ""
image:
  pullPolicy: Always
  repository: us-west1-docker.pkg.dev/devopsre/social-connect/odis-signer
  tag: "odis-signer-3.1.1"
imagePullSecrets: []
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts: 
    - host: odis-signer1-mainnet.rc1-europe-west1.celo-testnet.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: odis-signer1-mainnet.rc1-europe-west1.celo-testnet.org-tls
      hosts:
        - odis-signer1-mainnet.rc1-europe-west1.celo-testnet.org
livenessProbe: {}
nameOverride: ""
nodeSelector:
  node.kubernetes.io/instance-type: e2-standard-4
podAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "3000"
  prometheus.io/scrape: "true"
podSecurityContext: {}
readinessProbe: {}
replicaCount: 1
resources:
  requests:
    cpu: 1000m
    memory: 1Gi
securityContext: {}
serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: odis-signer1-mainnet@celo-testnet-production.iam.gserviceaccount.com
  create: true
  name: ""
tolerations:
  - key: "service"
    operator: "Equal"
    value: "odis"
    effect: "NoSchedule"
