coverage:
  status:
    project:
      default:
        target: auto
        threshold: null
        removed_code_behavior: adjust_base
      odis:
        paths:
          - packages/phone-number-privacy
      sdk:
        paths:
          - packages/sdk
    patch: off
