name: Request Identifier
description: File a request to add a new identifier type to Social-Connect
title: "[Identifier Request]: "
body:
    - type: input
      id: identifier
      attributes:
          label: Identifier Name
          description: "Which identifier would you like to add?"
          placeholder: "Example: Twitter, Discord, Instagram, Telegram, etc..."
      validations:
          required: true
    - type: input
      id: prefix
      attributes:
          label: Preferred Prefix
          description: "What would be a preferred prefix for the same?"
          placeholder: "Example: twit, discord, github, phone, mail, tel, etc..."
    - type: markdown
      attributes:
          value: |
              In order to add support for the requested identifier, you can add support for the identifier [here](https://github.com/celo-org/social-connect/tree/main/packages/odis-identifiers/src/identifier.ts) and open a PR.
