affinity:
  podAntiAffinity: 
    preferredDuringSchedulingIgnoredDuringExecution: 
    - weight: 100  
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In 
            values:
            - odis-signer
        topologyKey: kubernetes.io/hostname
autoscaling:
  enabled: false
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
env:
  api:
    domainsAPIEnabled: true
    pnpAPIEnabled: true
  blockchain:
    blockchainApiKeyExistingSecret: odis-signer0-forno-key
    blockchainProvider: https://alfajores-forno.celo-testnet.org
    fullNodeTimeoutMs: 10000
  db:
    cloudSqlProxy: false
    database: phoneNumberPrivacy
    host: odis-signer0-alfajores-db-postgresql-hl
    passwordExistingSecret: odis-signer0-db-password
    port: 5432
    type: postgres
    useSsl: false
    username: cLabs
    poolMaxSize: 100
    timeout: 10000
  keystore:
    domainsKeyLatestVersion: null
    domainsKeyNameBase: odis-signer0-alfajores-domains
    gcp:
      projectID: celo-testnet-production
    pnpKeyLatestVersion: null
    pnpKeyNameBase: odis-signer0-alfajores-phoneNumberPrivacy
    type: GoogleSecretManager
  log:
    format: stackdriver
    level: trace
  odis:
    mockDek: 0x034846bc781cacdafc66f3a77aa9fc3c56a9dadcd683c72be3c446fee8da041070
    odisSignerTimeout: "10000"
    shouldMockAccountService: "false"
    shouldMockRequestService: "false"
    testQuotaBypassPercentage: "0"
  tracing:
    enabled: true
    endpoint: "http://grafana-agent.monitoring:14268/api/traces"
    serviceName: "odis-signer0-alfajores-k8s"
fullnameOverride: ""
image:
  pullPolicy: Always
  repository: us-west1-docker.pkg.dev/devopsre/social-connect/odis-signer
  tag: "odis-signer-3.1.1"
imagePullSecrets: []
ingress:
  annotations: {}
  className: nginx
  enabled: false
  hosts: []
  tls: []
livenessProbe: {}
nameOverride: ""
nodeSelector:
  node.kubernetes.io/instance-type: e2-standard-4
podAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "3000"
  prometheus.io/scrape: "true"
podSecurityContext: {}
readinessProbe: {}
replicaCount: 1
resources:
  requests:
    cpu: 1000m
    memory: 1Gi
securityContext: {}
serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: odis-signer0-alfajores@celo-testnet-production.iam.gserviceaccount.com
  create: true
  name: ""
tolerations:
  - key: "service"
    operator: "Equal"
    value: "odis"
    effect: "NoSchedule"
